// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $allpj from "./routes/allpj.tsx";
import * as $buscarpj from "./routes/buscarpj.tsx";
import * as $crearpj from "./routes/crearpj.tsx";
import * as $eliminarpj from "./routes/eliminarpj.tsx";
import * as $index from "./routes/index.tsx";
import * as $buscador from "./islands/buscador.tsx";
import * as $creador from "./islands/creador.tsx";
import * as $deletebutton from "./islands/deletebutton.tsx";
import * as $eliminador from "./islands/eliminador.tsx";
import * as $todospersonbutton from "./islands/todospersonbutton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/allpj.tsx": $allpj,
    "./routes/buscarpj.tsx": $buscarpj,
    "./routes/crearpj.tsx": $crearpj,
    "./routes/eliminarpj.tsx": $eliminarpj,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/buscador.tsx": $buscador,
    "./islands/creador.tsx": $creador,
    "./islands/deletebutton.tsx": $deletebutton,
    "./islands/eliminador.tsx": $eliminador,
    "./islands/todospersonbutton.tsx": $todospersonbutton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
